#!/usr/bin/env bash
# Build the flowmap-flex-pi venvs from the exact pins in scripts/envs/locks/, next to the repo.
#
#   bash scripts/envs/install_envs.sh                 # all three
#   bash scripts/envs/install_envs.sh train libero    # any of: train libero robotwin
#
#   train     fm_env           training / inference / flow-map dev    (activate: env_flexpi.sh)
#   libero    fm_env_libero    + LIBERO simulator (mujoco 3.3.2)       (env_flexpi_libero.sh)
#   robotwin  fm_env_robotwin  + RoboTwin simulator (sapien, cuRobo)   (env_flexpi_robotwin.sh)
#
# PREFIX (default: the repo's parent directory) receives the venvs, their activation
# scripts, the uv cache (.uv_cache) and vulkan/nvidia_icd.json. Keep the uv cache on the
# same filesystem as the venvs: uv then hardlinks packages, so the three venvs share one
# copy of torch & co. An existing venv or activation script is never modified or
# replaced; that env is skipped. Refresh the locks from live envs with freeze_envs.sh.
#
# Needs uv and, on Snellius, Lmod (the EESSI 2025 stack: CUDA 12.8, FFmpeg 7). Elsewhere,
# provide CUDA 12.8 (CUDA_HOME, nvcc: cuRobo is compiled) and FFmpeg 4-7 yourself.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
PREFIX=${PREFIX:-$(dirname "$REPO")}
LOCKS=$REPO/scripts/envs/locks
PYTHON_VERSION=3.10.20
TORCH_INDEX=https://download.pytorch.org/whl/cu128
CUROBO_URL=https://github.com/NVlabs/curobo.git
CUROBO_COMMIT=0a50de1                 # the build fm_env_robotwin was made from
export UV_CACHE_DIR=${UV_CACHE_DIR:-$PREFIX/.uv_cache}

targets=("$@")
[ ${#targets[@]} -eq 0 ] && targets=(train libero robotwin)
for t in "${targets[@]}"; do
  case $t in train|libero|robotwin) ;; *) echo "unknown target '$t' (train, libero, robotwin)" >&2; exit 2 ;; esac
done
command -v uv >/dev/null || { echo "uv not found: https://docs.astral.sh/uv/getting-started/installation/" >&2; exit 1; }

log() { printf '\n[install_envs] %s\n' "$*"; }

load_modules() {
  if type module >/dev/null 2>&1; then
    set +u
    module load 2025 CUDA/12.8.0 FFmpeg/7.1.1-GCCcore-14.2.0
    set -u
    export CUDA_HOME=${EBROOTCUDA:-${CUDA_HOME:-}}
  fi
  [ -n "${CUDA_HOME:-}" ] || echo "[install_envs] warning: CUDA_HOME unset (DeepSpeed ops and cuRobo need CUDA 12.8)" >&2
}

# fm_env lock + flexpi + flowmap_core, all --no-deps: the lock is the complete package set,
# so nothing is re-resolved (that keeps robosuite's opencv/mujoco metadata out, see INSTALL.md).
build_base() {  # <venv name>
  local venv=$PREFIX/$1 lock=$LOCKS/$1.txt
  PY=$venv/bin/python
  uv venv --python "$PYTHON_VERSION" "$venv"
  # DeepSpeed is an sdist whose setup.py imports torch: build it after torch, without isolation.
  uv pip install --python "$PY" --no-deps --index-strategy unsafe-best-match \
    --extra-index-url "$TORCH_INDEX" -r <(grep -v '^deepspeed==' "$lock")
  uv pip install --python "$PY" --no-deps --no-build-isolation "$(grep '^deepspeed==' "$lock")"
  uv pip install --python "$PY" --no-deps -e "$REPO" -e "$REPO/flowmap_core"
}

# Installed package set == lock (plus the editable installs)?
verify() {  # <venv name>
  local venv=$PREFIX/$1
  if diff <(uv pip freeze --python "$venv/bin/python" | grep -v -E '^-e |^(flexpi|flowmap-core|nvidia-curobo)[=@ ]') \
          "$LOCKS/$1.txt" >/dev/null; then
    log "$1: package set matches locks/$1.txt"
  else
    log "$1: WARNING package set differs from locks/$1.txt:"
    diff <(uv pip freeze --python "$venv/bin/python" | grep -v -E '^-e |^(flexpi|flowmap-core|nvidia-curobo)[=@ ]') \
         "$LOCKS/$1.txt" || true
  fi
}

write_activate() {  # <script name> <venv name> <banner> <extra lines>
  local f=$PREFIX/$1
  if [ -e "$f" ]; then log "$f exists, left as is"; return; fi
  cat > "$f" <<EOF
# shellcheck shell=bash
# flowmap-flex-pi environment: $3
#
#   source $f
#
# Generated by scripts/envs/install_envs.sh. Loads the EESSI 2025 stack (CUDA 12.8 +
# FFmpeg 7) when Lmod is present, activates the uv venv \`$2\`, and exports the
# weight/cache locations every train/eval/serve entry point reads. Safe under \`set -u\`.

case \$- in *u*) _flexpi_had_u=1 ;; *) _flexpi_had_u=0 ;; esac
set +u

if type module >/dev/null 2>&1; then
  module load 2025                          # software-stack year
  module load CUDA/12.8.0                   # nvcc for DeepSpeed / cuRobo; matches torch cu128
  module load FFmpeg/7.1.1-GCCcore-14.2.0   # libavcodec.so.61 (ffmpeg 7) for torchcodec
  export CUDA_HOME="\$EBROOTCUDA"
fi

source $PREFIX/$2/bin/activate
$4
export FLEXPI_ROOT=$REPO
export DIFFSYNTH_MODEL_BASE_PATH="\$FLEXPI_ROOT/checkpoints"     # Wan2.2 + ActionDiT weights
export HF_HOME=$PREFIX/.hf_home                                  # DINOv3 (timm) + HF datasets
export UV_CACHE_DIR=$UV_CACHE_DIR

export NVCC_PREPEND_FLAGS="\${NVCC_PREPEND_FLAGS:-}"            # guards for launchers' set -u
export NVCC_APPEND_FLAGS="\${NVCC_APPEND_FLAGS:-}"
export PYTHONNOUSERSITE=1                                        # don't let ~/.local shadow the venv
export PYTORCH_CUDA_ALLOC_CONF="\${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

[ "\$_flexpi_had_u" = 1 ] && set -u
unset _flexpi_had_u
echo "[$1] $2 active | CUDA=\$(basename "\${CUDA_HOME:-none}") | weights=\$DIFFSYNTH_MODEL_BASE_PATH"
EOF
  log "wrote $f"
}

install_train() {
  build_base fm_env
  verify fm_env
  write_activate env_flexpi.sh fm_env "training / inference / flow-map dev" ""
}

install_libero() {
  # LIBERO is a submodule used through PYTHONPATH, never pip-installed (docs/INSTALL.md §4.2).
  [ -e "$REPO/third_party/LIBERO/libero" ] || git -C "$REPO" submodule update --init third_party/LIBERO
  build_base fm_env_libero
  verify fm_env_libero
  write_activate env_flexpi_libero.sh fm_env_libero "LIBERO evaluation (mujoco 3.3.2, robosuite 1.4.0)" \
'export PYTHONPATH="'"$REPO"'/third_party/LIBERO:'"$REPO"'/src:${PYTHONPATH:-}"
unset LIBERO_CONFIG_PATH                                         # let prepare_libero derive the binding'
}

install_robotwin() {
  local rt=$REPO/third_party/RoboTwin site
  build_base fm_env_robotwin
  site=$("$PY" -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
  # The two source patches of RoboTwin's script/_install.sh (both idempotent).
  sed -i -E 's/("r")(\))( as)/\1, encoding="utf-8") as/g' "$site/sapien/wrapper/urdf_loader.py"
  sed -i -E 's/(if np.linalg.norm\(delta_twist\) < 1e-4 )(or collide )(or not within_joint_limit:)/\1\3/g' \
    "$site/mplib/planner.py"
  # cuRobo: gitignored checkout, compiled CUDA extensions (several minutes).
  if [ ! -d "$rt/envs/curobo" ]; then
    git clone "$CUROBO_URL" "$rt/envs/curobo"
    git -C "$rt/envs/curobo" checkout "$CUROBO_COMMIT"
  fi
  (cd "$rt/envs/curobo" && TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST:-8.0;9.0}" \
     uv pip install --python "$PY" --no-deps --no-build-isolation -e .)
  verify fm_env_robotwin
  # SAPIEN renders through Vulkan; the GPU nodes register no NVIDIA ICD.
  if [ ! -e "$PREFIX/vulkan/nvidia_icd.json" ]; then
    mkdir -p "$PREFIX/vulkan"
    cat > "$PREFIX/vulkan/nvidia_icd.json" <<'EOF'
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.277"
    }
}
EOF
  fi
  write_activate env_flexpi_robotwin.sh fm_env_robotwin "RoboTwin evaluation (sapien, mplib, cuRobo)" \
"export VK_ICD_FILENAMES=$PREFIX/vulkan/nvidia_icd.json   # SAPIEN renders through Vulkan"
  if [ ! -d "$rt/assets/embodiments" ]; then
    log "RoboTwin assets missing (16 GB, gitignored): source $PREFIX/env_flexpi_robotwin.sh && cd $rt && bash script/_download_assets.sh"
  fi
}

load_modules
for t in "${targets[@]}"; do
  venv=$PREFIX/$(case $t in train) echo fm_env ;; *) echo "fm_env_$t" ;; esac)
  if [ -e "$venv" ]; then log "$venv exists, skipping '$t' (remove or rename it to rebuild)"; continue; fi
  log "building '$t' into $venv"
  "install_$t"
done
log "done (PREFIX=$PREFIX)"
